global using Microsoft.EntityFrameworkCore;
global using Ordering.Domain.Models;
global using Ordering.Domain.ValueObjects;
global using System.Reflection;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Ordering.Infrastructure.Data;
global using Ordering.Domain.Abstractions;